### ISSUE TITLE
`pub use` for common parts of tungstenite

### ISSUE THREAD

**Issue by WyseNynja** [snapview/tokio-tungstenite#109]
My code has both tokio-tungstenite and tungstenite as dependencies in its Cargo.toml. If tokio-tungstenite had a `pub use tungstenite::Message`, then I could import from tokio-tungstenite and track versions easier.

I noticed this because I tried to upgrade `tungstenite` while `tokio-tungstenite` is still using the old version (https://github.com/snapview/tokio-tungstenite/issues/108)

**Comment by sdroege** [comment]
All of tungstenite is re-exported from tokio-tungstenite: https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L19

**Comment by WyseNynja** [comment]
Oh perfect. I wonder how I missed that. Thank you!
