### ISSUE TITLE
Documentation for connect_async is incorrect

### ISSUE THREAD

**Issue by shepmaster** [snapview/tokio-tungstenite#113]
The documentation for [`connect_async`](https://docs.rs/tokio-tungstenite/0.10.1/tokio_tungstenite/fn.connect_async.html) states:

```rust
pub async fn connect_async<R>(
    request: R
) -> Result<(WebSocketStream<TcpStream>, Response), Error> 
where
    R: IntoClientRequest + Unpin, 
```

However, if you look at the source it shows `AutoStream`:

```rust
pub async fn connect_async<R>(
    request: R,
) -> Result<(WebSocketStream<AutoStream<TcpStream>>, Response), Error>
where
    R: IntoClientRequest + Unpin,
```

**Comment by shepmaster** [comment]
Some discussion with rustdoc folks suggest that this may be due to the fact that `AutoStream` is a transparent type alias without `--features tls`: 

https://github.com/snapview/tokio-tungstenite/blob/317569dfe0da6374476bf8048bf861902643b79b/src/connect.rs#L63

This is not a feature-union safe API definition. You may wish to instead be using a newtype instead.

**Comment by application-developer-DA** [comment]
Thanks, that's a good point indeed.

**Comment by application-developer-DA** [comment]
Seems to have been addressed in the newest versions 🙂
