### ISSUE TITLE
Close SplitSink with CloseFrame

### ISSUE THREAD

**Issue by Voronar** [snapview/tokio-tungstenite#117]
Hi.
Is there a way to close `SplitSink` part of `tokio_tungstenite::WebSocketStream` with closing code and reason like with https://docs.rs/tokio-tungstenite/0.11.0/tokio_tungstenite/struct.WebSocketStream.html#method.close?

In my case I have a web socket server with HashMap of peer address and writing stream (splitted part from `WebSocketStream`) in order to track user sessions, write to these users and close their connections.
But I can not put whole `WebSocketStream` (in order to close socket stream with code and reason) in hash map after creation with https://docs.rs/tokio-tungstenite/0.11.0/tokio_tungstenite/fn.accept_hdr_async.html because it is moved and can not be splitted later.

**Comment by Voronar** [comment]
I found the way with sending message to writing part of stream with closing message (https://docs.rs/tungstenite/0.11.1/tungstenite/enum.Message.html#variant.Close).

**Comment by application-developer-DA** [comment]
Yes, this is the right way :)
