### ISSUE TITLE
is it possible to access stream from multiple threads or multiple spawns ?

### ISSUE THREAD

**Issue by trila** [snapview/tokio-tungstenite#123]
Hi!
I tried to access the stream by wrapping it in Arc<Mutex<stream>> from multiple threads, but the send() function does nothing at all.
Is it correct to do so, or I can only access the stream from the thread which it connects in?

**Comment by application-developer-DA** [comment]
What do you mean by "but the send() function does nothing at all"?

I think this question is more related to Tokio than to Tungstenite. But generally speaking if you have `Send` and `Sync` object, then you can access it from multiple threads.
