### ISSUE TITLE
tokio = "0.3.0"

### ISSUE THREAD

**Issue by incker** [snapview/tokio-tungstenite#126]
New version of tokio is released
current version of tokio is 0.2 Cargo.toml

Better upgrade, to avoid downloading two versions of tokio in projects

**Comment by Urhengulas** [comment]
@agalakhov, @application-developer-DA: If it is okay, I will have a quick look what needs to be done to update 😄

**Comment by Urhengulas** [comment]
Fixed by https://github.com/snapview/tokio-tungstenite/pull/125
