### ISSUE TITLE
Add tokio-rustls feature

### ISSUE THREAD

**Issue by Redrield** [snapview/tokio-tungstenite#127]
All in the title, add a feature allowing use of rustls instead of native-tls, I'd be willing to work on this

**Comment by Redrield** [comment]
The `tls` feature of tungstenite requires native-tls for wrapping the stream, so it looks like I'd have to add a rustls feature there first before being able to work on this.

**Comment by sdroege** [comment]
Note that [async-tungstenite](https://crates.io/crates/async-tungstenite) can optionally use `tokio-rustls`. Feel free to merge the code required for that into tokio-tungstenite.

**Comment by dnaka91** [comment]
Just opened a PR that adds `rustls` support to `tungstenite` (https://github.com/snapview/tungstenite-rs/pull/166). If that gets (hopefully) merged, then I will prepare a PR here as well to add `rustls` support.
