### ISSUE TITLE
Server side support for verifying protocol and custom headers

### ISSUE THREAD

**Issue by jq-rs** [snapview/tokio-tungstenite#13]
client_async() allows now to let the user initiate the WebSocket handshake with extra headers. Similar support could be added to server side too, at least the ability to verify protocol would be great.

**Comment by application-developer-DA** [comment]
Yes, we want to extend this part and plan to implement this sooner or later. See https://github.com/snapview/tungstenite-rs/issues/6 and https://github.com/snapview/tokio-tungstenite/issues/9
