### ISSUE TITLE
Is it possible to set the local_address of a client?

### ISSUE THREAD

**Issue by auterium** [snapview/tokio-tungstenite#131]
Hi there 👋 

I have multiple IPs bounded to my NIC and I would like to be able to control which IP to use when creating a client connection to a WS server. I've been looking atound the docs but all I can find is a way to read the `local_addr` after the connection is open.

Based on the research I've done so far, seems like `tokio` itself doesn't provide this capability and instead `socket2` is [recommended for this](https://stackoverflow.com/a/59916539) (even mentioned in `tokio` v0.3 regarding `TcpListener::from_std()`). I'm by no means an expert in this domain, so is this a good idea? Is there any alternative? Thanks

**Comment by application-developer-DA** [comment]
Yeah, I think that would probably work. I.e. create `TcpStream` and set the `local_addr` for it, then "convert" it to the tokio's `TcpStream` and then pass it to the `tokio-tungstenite`'s `client_async_tls` or other function that takes an abstract stream.

**Comment by application-developer-DA** [comment]
Hopefully the question has been answered :)
