### ISSUE TITLE
[Question] How to explicitly enable SNI?

### ISSUE THREAD

**Issue by wbrickner** [snapview/tokio-tungstenite#132]
Hello,

I need to connect to a server that forces the client to support SNI.
I continue to get an automatic disconnection when trying to write to my tx stream: `AlreadyClosed`,
however I don't get a `Close` message, and I don't get an error in the connection stage.

Could this be a lack of SNI? It's almost as if the connection is never *actually* opened, as I never get any messages and cannot send messages. If this might be the issue, how can I enable SNI?

Thanks.

**Comment by agalakhov** [comment]
Tungstenite uses SNI implicitly. Yes, it could be SNI-related, but I'd rather check certificates first.

**Comment by wbrickner** [comment]
Thank you, I could not find the TLS feature set documented anywhere so I assumed SNI was not supported, perhaps the supported / default TLS features should be documented prominently.

I am used to working in environments in which the network layer is essentially handled for you, so things like certificate validation and SNI are not something I need to think about.  With that said, and assuming SNI is being used, are there subtleties in configuration / usage?

I must be doing something wrong, because everything works by default when connecting from something like Node.js's `ws` package, and when using `tokio-tungstenite` to connect to other TLS hosts things work as expected, but this specific host I am connecting to through `tokio-tungstenite` is not working.

Would you be willing hazard a guess as to the issue? I'm a bit stuck.  It's nothing obvious, I get an `HTTP 101` with a `connection: upgrade` and `upgrade: websocket` header as expected.

**Comment by wbrickner** [comment]
Whoops, I was not communicating with the WebSocket API in the correct way in my `tokio-tungstenite` impl, that was my issue.

Apologies for any confusion, thank you for clearing up the usage of SNI.
