### ISSUE TITLE
Intercept HTTP requests

### ISSUE THREAD

**Issue by alecmocatta** [snapview/tokio-tungstenite#134]
It looks like it might be possible on the sync `tungstenite` crate to hook the handshake and manually return HTTP responses if, for example, you want to run Websocket and HTTP servers on the same port.

I can't see a way to do this with `tokio-tungstenite` however, unless I'm overlooking something? I tried passing a `callback` to `accept_hdr_async_with_config` but requests fail before invoking it with "No "Connection: upgrade" in client request".

**Comment by agalakhov** [comment]
Basically you're expected to do exactly the opposite. You take some HTTP request processor (framework?) and hook Tungstenite to it.

**Comment by alecmocatta** [comment]
Okay, thanks @agalakhov. So am I right in thinking I would have to drop down from `tokio-tungstenite`, interact directly with `tungstenite`, and copy a lot of the relevant tokio integration from `tokio-tungstenite`?

**Comment by agalakhov** [comment]
You can use `tokio-tungstenite` without copying anything. Call `WebSocketStream::from_raw_socket()` or `from_partially_read()` after performing the handshake. Most HTTP frameworks will do the handshake for you. We just use `warp` in our projects.

**Comment by application-developer-DA** [comment]
Indeed, in fact `warp` uses `tokio-tungstenite`, so you can check their source code to see how they achieved the integration.

**Comment by alecmocatta** [comment]
Ah, indeed `warp` uses `from_raw_socket`. That clarifies things, thank both!
