### ISSUE TITLE
Close frame not delivered through WebSocketStream::next on Windows 10

### ISSUE THREAD

**Issue by 2bdkid** [snapview/tokio-tungstenite#136]
I have a websocket server running on a host in my network, and I'm running into an issue creating a client program with tokio-tungstenite. I isolated the code with issues to this:

```
use futures_util::StreamExt;
use tokio_tungstenite::tungstenite::protocol::CloseFrame;
use tokio_tungstenite::tungstenite::protocol::frame::coding::CloseCode;

#[tokio::main]
async fn main() {
    let (mut websocket, _rsp) = tokio_tungstenite::connect_async("ws://192.168.1.254:5688")
        .await
        .expect("couldn't connect to websocket");

    let close_frame = CloseFrame {
        code: CloseCode::Away,
        reason: Default::default(),
    };
    
    websocket.close(Some(close_frame)).await.expect("issue closing websocket");
    println!("closed");

    for _ in 0..3 {
        let rsp = websocket.next().await;
        println!("{:?}", rsp);
    }
}
```

These are the library versions I'm using:

```
tokio = { version = "0.3", features = ["full"] }
tokio-tungstenite = "0.12.0"
futures-util = "0.3.8"
```

When I run this code on Windows, it hangs in the for loop. For instance, I see:

```
closed
Some(Ok(Binary([161, 107, 98, 114, 97, 100, 121, 45, 115, 99, 97, 108, 101, 251, 191, 199, 221, 109, 149, 213, 77, 53])))
```
but it hangs here. When I run this code from a Linux host, it behaves as expected.

```
closed
Some(Ok(Binary([161, 107, 98, 114, 97, 100, 121, 45, 115, 99, 97, 108, 101, 251, 191, 189, 39, 104, 207, 242, 149, 197])))
Some(Ok(Close(Some(CloseFrame { code: Away, reason: "" }))))
None
```

Since I can't include all of the websocket server code, I captured a packet trace through wireshark, it just includes the client close frame, one server binary frame, then the server close frame - that's the frame not being delivered through `next()` on Windows.

[trace.pcapng](https://drive.google.com/file/d/1hPe0wV1X8Po7t3BMruM1Nf0YYrcKpeqj/view?usp=sharing)

**Comment by application-developer-DA** [comment]
This seems to be an issue with the configuration of the server or the machine, I could not reproduce the same issue locally. The Wireshark log seems to be incomplete, I was not able to spot WebSocket communication (perhaps due to the missing handshake in the log Wireshark was not able to "detect" it), but rather 3 TCP packets which makes analysis a bit harder.

In case you can reproduce it locally and you're sure it's tungstenite, feel free to re-open, debug logs would be useful as well.
