### ISSUE TITLE
Support accepting unmasked client frames

### ISSUE THREAD

**Issue by adambezecny** [snapview/tokio-tungstenite#138]
hi,

we are building Telephony gateway solution utilizing asterisk (https://www.asterisk.org/), audio fork (https://github.com/nadirhamid/asterisk-audiofork) and node.js (using ws lib -https://github.com/nadirhamid/asterisk-audiofork ). Everything just works fine. Audiofork is special asterisk extension that can connect as a client to websocket server and start streaming audio data once call is connected.

Recently we are experimenting with Rust. For websocket server we are using tokio-tungstenite

We are getting this error: https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L453

Is it possible somehow to make tokio-tungstenite not to  enforce frames masking (even though this is not good thing and is not compliant with RFC 6455)?  Since our Node.JS app works fine I guess they are simply unmasking payload if it is masked otherwise they simply ignore the mask flag (https://github.com/websockets/ws/blob/master/lib/receiver.js#L347).

Are you aware of any other Rust WS implementation that would not require client frames to be masked?

I have also created counter issue on asterisk-audiofork: https://github.com/nadirhamid/asterisk-audiofork/issues/7

**Comment by agalakhov** [comment]
One could add an option to violate RFC for interacting with broken peers.

**Comment by adambezecny** [comment]
any chance this could be added soon? I just tried warp just to find out it is internally using tokio-tungstenite hence throwing the very same error :)

**Comment by agalakhov** [comment]
Feel free to send a pull request :)

**Comment by adambezecny** [comment]
I have prepared and tested the change  locally. It is change in https://github.com/snapview/tungstenite-rs repo. Nevertheless I am not able to push new branch:

C:\Projects\tungstenite-rs>git push origin uframes
remote: Permission to snapview/tungstenite-rs.git denied to adambezecny.

Can you give me the permission so that I can push my branch and create PR?

**Comment by strohel** [comment]
@adambezecny thanks for preparing this.

The GitHub workflow is slightly different - contributors do not push directly to upstream repository. Instead, contributors are encouraged to **fork** the upstream repository (a button here in UI), clone _the fork_ locally, push their new branch to the fork, then open pull request from the fork to the upstream repo.

Could you please do it this way? It may involve changing the remote origin url of your local git repository checkout (easy).

**Comment by adambezecny** [comment]
sorry for confusion, doing it for the first time. PR created: https://github.com/snapview/tungstenite-rs/pull/159

**Comment by application-developer-DA** [comment]
Closed by https://github.com/snapview/tungstenite-rs/pull/159
