### ISSUE TITLE
tcplistener accept() in tokio-spawned thread cannot catch client connect request 

### ISSUE THREAD

**Issue by jonghne** [snapview/tokio-tungstenite#140]
Hi, refer to the example, https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs, I need to run websocket server in thread, the codes are like:
tokio::spawn(async move {
.....
let listener = TcpListener::bind(url).await.unwrap();
while let Ok((stream, addr)) = listener.accept().await {
        tokio::spawn(handle_connection(state.clone(), stream, addr));
    }
......
})

the bind() could be executed , but never enter handle_connection(), it seems accept not working. what's the problem? thank you.

**Comment by application-developer-DA** [comment]
Apparently there are either no incoming client requests (thus accept does not return anything) or it fails (i.e. does not return `Ok(..)`). Unfortunately there is not enough information to tell more. It is not related to `tungstenite` or `tokio-tunstenite` and seems to be some error in the configuration or something like this (like mixing TLS-encrypted and normal connections etc), thus I'm going to close it, but feel free to re-open if you find any issues with WebSockets. 

I would suggest trying to log the actions, like checking if `accept()` accepts anything at all and check if there is an error returned.
