### ISSUE TITLE
Using tokio 1.0.0 which has been yanked

### ISSUE THREAD

**Issue by paulirotta** [snapview/tokio-tungstenite#148]
https://crates.io/crates/tokio/versions

We could relax this dependency to tokio 1.0

I'll put in a PR

**Comment by strohel** [comment]
> I'll put in a PR

I think there is no need for it: dependency of `1.0.0` means >= 1.0.0 and < 2.0.0. See https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio

@application-developer-DA, shall we close this?

**Comment by paulirotta** [comment]
Sure. Please also close the PR as appropriate

**Comment by paulirotta** [comment]
Yeah, my bad. I'll close the PR

**Comment by strohel** [comment]
No probs, have a nice day.

**Comment by paulirotta** [comment]
@strohel Sorry to noob on you, but according to https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html the quotes below make it sound like it _should_ have had an effect, but when I look at Cargo.lock it confirms you are right and it does not have an effect. Is that because it is a library dependency?

_"The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement."

..

"^0.0.3  :=  >=0.0.3, <0.0.4"_
