### ISSUE TITLE
Unable to connect using connect_async

### ISSUE THREAD

**Issue by sammoh94** [snapview/tokio-tungstenite#161]
I am trying to use `connect_async` to setup a simple client to connect to and read from a websocket. Here is my code:

```
use tokio_tungstenite::connect_async;

#[tokio::main]
async fn main() {
    let url = url::Url::parse("wss://echo.websocket.org").unwrap();

    match connect_async(url).await {
        Ok(_connection) => {}
        Err(error) => {
            println!("{:?}", error);
        }
    }
}
```
I am getting a `HandshakeIncomplete` error here. Separately, when I run `websocat 'wss://echo.websocket.org'`, I am able to connect. Any ideas on what may be the issue. Thanks!

FYI: I am using v0.14.0 for tokio-tungstenite and 1.4 for tokio

**Comment by application-developer-DA** [comment]
You must be trying to connect to the endpoint that accepts only the TLS connections using the plain web sockets. Please consider specifying the corresponding TLS feature when using `tokio-tungstenite`, you can choose either of these: https://github.com/snapview/tokio-tungstenite/blob/master/Cargo.toml#L15

**Comment by sammoh94** [comment]
Ah thank you! 

@application-developer-DA a followup question (let me know if I should post as a separate issue)

I setup a websocket server and am using the `accept_hdr_async` function. If the handshake fails, I am setting the ErrorResponse like so:

```
fn generate_error_response(error_message: &str) -> ErrorResponse {
    let response = ErrorResponse::new(Some(error_message.to_string()));
    let (mut parts, body) = response.into_parts();
    parts.status = StatusCode::BAD_REQUEST;
    
    ErrorResponse::from_parts(parts, body)
}
```
The response I get correctly contains the status as 400 but the body is None even though I confirmed that the body is set above. Any idea what is preventing the body from showing up in the client?

The response that the client sees looks as follows:
```
Http(Response { status: 400, version: HTTP/1.1, headers: {}, body: None })
```

**Comment by inferrna** [comment]
Got same error after update to 0.14 and provide by mistake feature **rustls** instead of **rustls-tls**
