### ISSUE TITLE
ErrorResponse body showing up as None

### ISSUE THREAD

**Issue by sammoh94** [snapview/tokio-tungstenite#162]
I setup a websocket server and am using the `accept_hdr_async` function. If the handshake fails, I am setting the ErrorResponse like so:

```
fn generate_error_response(error_message: &str) -> ErrorResponse {
    let response = ErrorResponse::new(Some(error_message.to_string()));
    let (mut parts, body) = response.into_parts();
    parts.status = StatusCode::BAD_REQUEST;
    
    ErrorResponse::from_parts(parts, body)
}
```
The response I get correctly contains the status as 400 but the body is None even though I confirmed that the body is set above. Any idea what is preventing the body from showing up in the client?

The response that the client sees looks as follows:
```
Http(Response { status: 400, version: HTTP/1.1, headers: {}, body: None })
```

**Comment by application-developer-DA** [comment]
I believe it's because of this: https://docs.rs/tungstenite/0.13.0/src/tungstenite/handshake/client.rs.html#150
