### ISSUE TITLE
More examples and documentation needed

### ISSUE THREAD

**Issue by petar-dambovaliev** [snapview/tokio-tungstenite#169]
It can be confusing to understand how the client connection has to be established because the client request type is not documented and there are not enough examples for it.
https://github.com/snapview/tungstenite-rs/blob/master/src/handshake/client.rs#L24

In result, i created a manual request doing the http upgrade and then connect.
Then, i got an error when i closed the stream because the closing handshake wasn't performed.

```
 let req = client
        .get("http://127.0.0.1:3000/my_path")
        .header(CONNECTION, "upgrade")
        .header(UPGRADE, "websocket")
        .header(SEC_WEBSOCKET_KEY, convert_key("password".as_bytes()))
        .build()
        .unwrap();
        
let (mut ws_stream, _) = connect_async("ws://127.0.0.1:3000")
```

This is why i suggest that examples and documentation being added for the client request type.
It isn't obvious that you should do `client_async("ws://127.0.0.1:3000/my_path", stream)`
then path at the end would only be used for the initial handshake and so on.

**Comment by application-developer-DA** [comment]
I'm not sure that I got your concern. In your example you're creating `req` that is not passed to any function, relying on `connect_async`, at the same time you mention the `client_async()`, so I'm not sure I understood which function created confusion. I also did not get what you mean by "path at the end would only be used for the initial handshake and so on".

The documentation [is in our docs](https://docs.rs/tokio-tungstenite/0.14.0/tokio_tungstenite/).

There is also [several examples](https://github.com/snapview/tokio-tungstenite/tree/master/examples) that show different ways to connect, including the usage of `connect_async` that does not require passing the stream.

But for concrete suggestions or improvements the PRs are welcome ;)

**Comment by petar-dambovaliev** [comment]
> I'm not sure that I got your concern. In your example you're creating `req` that is not passed to any function, relying on `connect_async`, at the same time you mention the `client_async()`, so I'm not sure I understood which function was confusing for you. I also did not get what you mean by "path at the end would only be used for the initial handshake and so on".
> 
> The documentation [is in our docs](https://docs.rs/tokio-tungstenite/0.14.0/tokio_tungstenite/).
> 
> There is also [several examples](https://github.com/snapview/tokio-tungstenite/tree/master/examples) that show different ways to connect, including the usage of `connect_async` that does not require passing the stream.
> 
> But for concrete suggestions or improvements the PRs are welcome ;)

If I have a regular http server with a route as `/echo` that is upgrading the connection to web sockets, I would pass for example `ws://127.0.0.1:3000/echo`. What your crate would do is create an upgrade request internally and call the regular http route with a get method at `/echo`. Then it would connect on the websocket on `ws://127.0.0.1:3000`. Where is this behavior documented? The Request data structure and it's methods, as far as I saw have no documentation.

**Comment by application-developer-DA** [comment]
Hm... It is the WebSocket protocol, that is documented In the [WebSocket RFC](https://tools.ietf.org/html/rfc6455#section-1.2).
