### ISSUE TITLE
Question regarding the closing handshake for the WebSocketStream

### ISSUE THREAD

**Issue by cloutiertyler** [snapview/tokio-tungstenite#172]
I was reading through [this ticket](https://github.com/snapview/tokio-tungstenite/issues/119) and I was a bit confused about the procedure for closing the WebSocketStream. It sounds like you've also handled it differently on the client and server. If I understood correctly, if a `Message::Close` is received on the client, then the closing handshake has already been automatically completed, but if you receive a `Message::Close` on the server, you as the server user are responsible for completing the closing handshake. Is that accurate?

I'm personally particularly interested in getting it right on the server-side. Is the below code approximately how you imagined the library being used?

The following code probably doesn't compile because of ownership things, but it's conceptually the same logic as what I'm using.

```rust
let ws = ...
spawn(async move {
    let mut close_sent: bool = false;
    while let Some(message) = ws.next().await {
        match message {
            Ok(Message::Text(message)) => {
                println!("Received: {}", message);
                close_sent = true;
                ws.send(Message::Close(Some(CloseFrame {
                    code: CloseCode::Normal,
                    reason: "Message was received. Server closing connection normally.".into()
                }))).await;
            },
            Ok(Message::Binary(message)) => { ... }
            Ok(Message::Ping(message)) => { ... }
            Ok(Message::Pong(message)) => { ... }
            Ok(Message::Close(close_frame)) => {
                if !close_sent {
                    // The client has sent an unsolicited close frame.
                    // This means the client wishes to close the connection
                    // and will will send no further messages along the
                    // connection. Send a close frame to the client.
                    // Don't destroy the connection yet. Wait for the stream to end.
                    ws.send(Message::Close(Some(CloseFrame {
                        code: CloseCode::Normal,
                        reason: "Client requested connection close.".into()
                    }))).await;
                } else {
                    // There's no need to do anything here, because we're the ones
                    // that sent the initial close. The close frame we just received
                    // was an acknowledgement by the client (their side of the handshake)
                    // Maybe check their close frame or something
                }
            Err(error) => match error {
                tokio_tungstenite::tungstenite::Error::ConnectionClosed => {
                    // Do nothing. There's no need to listen to this error because
                    // according to the tungstenite documentation its really more of a
                    // notification anyway, and tokio-tungstenite will end the stream
                    // so we'll drop the websocket at after the while loop.
                }
                error => println!("Websocket receive error: {}", error)
            }
        }
    }
    // The stream is ended by tokio-tungsten when we receive a `ConnectionClosed` error. 
    // That's not actually an error, but rather a notification saying that the handshake has been
    // completed. At this point it's safe to drop the underlying connection.
    drop(ws)
});
```

My question is, does this demonstrate a correct example of how the server should handle the closing handshake?

**Comment by jxs** [comment]
Hi,
> It sounds like you've also handled it differently on the client and server. If I understood correctly, if a Message::Close is received on the client, then the closing handshake has already been automatically completed, but if you receive a Message::Close on the server, you as the server user are responsible for completing the closing handshake. Is that accurate?

when you `write_message` a `Message::Close` the behavior [is the same from Server or Client](https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L358). 
On the other end of the communication, as @application-developer-DA replied on that issue:

>  you will get the Message::Close on your side (in case you want to have some special behavior that depends on a close code). After that you will get ConnectionClosed which will signify that it's safe to drop the object. In other words: the documentation you referred to is still valid :)

`WebSocketStream` will end the stream after receiving `Message::Close` [see here](https://github.com/snapview/tokio-tungstenite/blob/287f477e5491296ed936aa075947740ea5d6ba7b/src/lib.rs#L274)

so you don't need to exchange  `Message::Close`  :)

**Comment by cloutiertyler** [comment]
> `WebSocketStream` will end the stream after receiving `Message::Close` [see here](https://github.com/snapview/tokio-tungstenite/blob/287f477e5491296ed936aa075947740ea5d6ba7b/src/lib.rs#L274)

Sorry, the code you linked doesn't show that the WebSocketStream sends the `Message::Close` automatically. It seems to just show that after you receive an `Error::ConnectionClosed` the stream will end. Am I responsible for sending the `Message::Close` acknowledgement or does that happen automatically somewhere?

**Comment by jxs** [comment]
>Sorry, the code you linked doesn't show that the WebSocketStream sends the Message::Close automatically. It seems to just show that after you receive an Error::ConnectionClosed the stream will end.

WebSocketStream doesn't send `Message::Close`, the code I linked shows that when Receiving `WsError::AlreadyClosed` (which is send after sending `Message::Close`) it returns `None` which ends the Stream. 

>So if I don't need to exchange the Message::Close, could you point me to the code that sends the Message::Close in response to the client's request to close?

It's [here](https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L557-L578) if state `WebSocketState::Active` a `Frame::close` is [replied back](https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L576)

**Comment by cloutiertyler** [comment]
Thank you!

**Comment by jxs** [comment]
no worries :)
you don't need to handle  `Error::ConnectionClosed` as it's already handled by the [`WebSocketStream`](https://github.com/snapview/tokio-tungstenite/blob/287f477e5491296ed936aa075947740ea5d6ba7b/src/lib.rs#L274). You probably also don't need `drop(ws)` as it goes out of scope after and is dropped implicitly

**Comment by cloutiertyler** [comment]
> no worries :)
> you don't need to handle `Error::ConnectionClosed` as it's already handled by the [`WebSocketStream`](https://github.com/snapview/tokio-tungstenite/blob/287f477e5491296ed936aa075947740ea5d6ba7b/src/lib.rs#L274). You probably also don't need `drop(ws)` as it goes out of scope after and is dropped implicitly

Makes sense, I just wanted to include both of those here to be explicit for anyone who was unclear on how it works. I mentioned in my comment that listening to the error is unnecessary. Thanks for the help and clarification!
