### ISSUE TITLE
Host name resolved into IP address results in connection error (0.14.0)

### ISSUE THREAD

**Issue by lejoow** [snapview/tokio-tungstenite#173]
I have a websocket adddress that looks like **wss://abc.com:9244** and with this address I have no issue establishing the connection using the tungstenite library. However, with the **tokio-tungstenite 0.14.0**,  I am getting a connection error. I did a little bit of debugging and found out that the IPV4 address that gets resolved in the TcpStream::connect function is wrong. 

For example, "**wss://abc.com:9244**" address gets resolved inside the **TcpStream:connect** function to some IPV4 address that looks like **42.58.48.124:9244**, however, with this IP address, I am unable to establish websocket connection to the host. 

Is there a way to use TcpStream::connect function so that it doesn't resolve the hostname into IP address before it attempts to connect? Or am I missing something completely and barking at the wrong tree..? any advice is appreciated. 

Thanks,

**Comment by application-developer-DA** [comment]
> I have a websocket adddress that looks like wss://abc.com:9244 and with this address I have no issue establishing the connection using the tungstenite library. However, with the tokio-tungstenite 0.14.0, I am getting a connection error. I did a little bit of debugging and found out that the IPV4 address that gets resolved in the TcpStream::connect function is wrong.

Hm. This is interesting. We rely upon the [`TcpStream::connect` from Tokio](https://docs.rs/tokio/1.6.1/tokio/net/struct.TcpStream.html#method.connect) to connect to the remote endpoint in `tokio-tungstenite`, according to documentation of which, it will try to resolve and connect to each of the addresses in case the endpoint has multiple IP addresses. Can you confirm that it fails during the `TcpStream:connect` stage (i.e. that it's the `TcpStream::connect` that returns the error)?

**Comment by application-developer-DA** [comment]
Yeah, interesting. Could you narrow down the cause to `TcpStream` vs `tokio_dns` only and create some small SSSCE? 

I'm asking because if it's the problem with `TcpStream`, then it's not related to `tungstenite-rs` directly, but rather to the standard library, in which case it would make sense to open a bug there.

**Comment by application-developer-DA** [comment]
There has been no updates since a months, so I'm going to close this issue as it seems to be stale. But if you have any news or interesting insight, let us know ;)
