### ISSUE TITLE
TLS feature example for wss server

### ISSUE THREAD

**Issue by incker** [snapview/tokio-tungstenite#176]
Hello,

You have added ​documentation about TLS features to README, but any way I think people (and me also) find it hard to build websocket server over TLS, and there are no examples in internet.

So adding a wss example server will be a lot useful. Or maybe reply to this issue, will be indexed by google and will be helpful.

Any way, thank you a lot for cool crate

**Comment by Voronar** [comment]
https://github.com/snapview/tungstenite-rs/issues/127

**Comment by jxs** [comment]
Hi, thanks for your interest! And thanks @Voronar, I am going to close this one in favor of #127 then
