### ISSUE TITLE
Missing tag for version 0.14

### ISSUE THREAD

**Issue by OnikenX** [snapview/tokio-tungstenite#181]
version 0.14 is released on crates.io but there is no tag for that release version in the repo

**Comment by OnikenX** [comment]
the bump happened in d70bd22175f5f6c342041321d1216af977f88bf5

**Comment by application-developer-DA** [comment]
Thanks, fixed.

The actual commit was `c3e76eae904af27d5aceb2950d58c05cfb67632d` (next commit after the bump that did a minor change).
