### ISSUE TITLE
Converting a actix_web::HttpRequest into a tungstenite::Request

### ISSUE THREAD

**Issue by mscofield0** [snapview/tokio-tungstenite#193]
I would like to use tokio_tungstenite instead of Actix's WebSockets for more manual fine tuning. However, I would need to implement `IntoClientRequest` on Actix's `HttpRequest`. I've tried doing it myself, but I'm not experienced enough in both Actix and tokio_tungstenite to do this. 

Can someone help me write a conversion implementation?

**Comment by mscofield0** [comment]
Not necessary anymore.

**Comment by kvzn** [comment]
@mscofield0 Have you found a way to do this?

**Comment by mscofield0** [comment]
I haven't, I just went with Actix's solution.
