### ISSUE TITLE
Is it possible to set a custom User Agent header value?

### ISSUE THREAD

**Issue by Themayu** [snapview/tokio-tungstenite#196]
Is it possible to set the `User-Agent` header value that will be sent along with the handshake request? This is important to me, as the WebSocket server I plan to communicate with requires that the header be set to differentiate client implementations.

**Comment by sdroege** [comment]
You can pass a [`http::Request`](https://docs.rs/http/0.2.4/http/request/struct.Request.html) into `connect_async()` that has all the extra headers you want to provide to the header.
