### ISSUE TITLE
Question about closing connection during a WebSocketStream fold.

### ISSUE THREAD

**Issue by LoganGoh** [snapview/tokio-tungstenite#199]
I have some code
```rust
    let (websocket_stream, _) = connect_async("my_url").await?;
    let (mut write, read) = websocket_stream.split();

    read.fold( 0, |acc, message| /* do stuff */);
```

During the fold, based on the input I receive from the websocket, I would like to close the connection. What's the correct way to do that? write has a close() function, but read does not. And I can't call read from within the fold function. I tried passing in either write or read into the fold, that doesn't work either.

**Comment by application-developer-DA** [comment]
Well, one of the ways to accomplish it is to have some `mpsc` channel and pass the `tx` part into the `fold()`'s closure. That way you could push messages to the `tx` and make other task be something like `rx.forward(write)`.
