### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by psmit** [snapview/tokio-tungstenite#202]
I'm looking for a way to specify a connection timeout on a client. Unfortunately, I am not finding this option in the documentation. This option is necessary, as otherwise misbehaving servers can block a client forever.

**Comment by jxs** [comment]
Hi there, can't you wrap [`connect_async`](https://docs.rs/tokio-tungstenite/0.16.0/tokio_tungstenite/fn.connect_async.html) with [`tokio::time::timeout`](https://docs.rs/tokio/1.14.0/tokio/time/fn.timeout.html#examples)?

**Comment by psmit** [comment]
Hmm, yes I can... I now see that I actually posted this question in the wrong repo, I wanted to do this without async...

**Comment by soulmachine** [comment]
@psmit I tried to use

```rust
let ret = tokio::time::timeout(
        std::time::Duration::from_secs(15),
        tokio_tungstenite::connect_async(url),
    )
    .await
    .unwrap();
```

to replace `let ret = tokio_tungstenite::connect_async(url).await;`

But it actually didn't work, the code still got stuck forever, I posted an issue here https://github.com/snapview/tokio-tungstenite/issues/220
