### ISSUE TITLE
accept_hdr_async refuse unauthorized connection

### ISSUE THREAD

**Issue by MainTobias** [snapview/tokio-tungstenite#205]
I am looking for a way to prevent WebSockets from opening when the initial HTTP request does not contain a valid jwt token. Currently, I have two ideas on how to do this:

`tokio_tungstenite::accept_hdr_async(raw_stream, auth)`
**1st idea**
```rust
fn auth(req: &Request, mut res: Response) -> Result<Response, ErrorResponse> {
    if let Some(pass) = req.headers().get("Authorization") {
        if pass.to_str().unwrap() != "123" {
            *res.status_mut() = StatusCode::FORBIDDEN;
        }
    } else {
        *res.status_mut() = StatusCode::UNAUTHORIZED;
    }
    Ok(res)
}
```

**2nd idea:**
```rust
fn auth(req: &Request, mut res: Response) -> Result<Response, ErrorResponse> {
    Err(ErrorResponse::default())
}
```
The problem with number 1 is that whether the WebSocket gets closed or not is up to the client and the WebSocket gets opened before it's closed. Problem with idea 2 is that that it throws thread 'tokio-runtime-worker' panicked at 'Error during the websocket handshake occurred: Protocol(CustomResponseSuccessful)' and a huge backtrace and I do not think that is optional. Also that the panic message says CustomResponseSuccesful throws me off. There must be a better way to do this.

**Comment by jxs** [comment]
Hi! I think you should verify those headers before the [upgrade](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade), [see how warp does it](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade) for example

**Comment by application-developer-DA** [comment]
> The problem with number 1 is that whether the WebSocket gets closed or not is up to the client and the WebSocket gets opened before it's closed.

Well, we can't fix the client that does not respect RFC. If the other part misbehaves and ignores the RFC, then we can't do anything about it.

> Problem with idea 2 is that that it throws thread 'tokio-runtime-worker' panicked at 'Error during the websocket handshake occurred: Protocol(CustomResponseSuccessful)' and a huge backtrace and I do not think that is optional.

This panic does not come from `tungstenite-rs` or `tokio-tungstenite`, it comes from the user code (your code). I believe you just copied the code from examples which was written with `expect()` to panic in case of error. So it's not the issue with the crate ;)

> Also that the panic message says CustomResponseSuccesful throws me off. There must be a better way to do this.

The error tells that it was the violation of protocol (as described in RFC), or in this particular case: that the callback returned an error, but the response from it has a successful HTTP error code. Failed responses must have an error code instead (and not HTTP 200 OK or something) This has to do with the fact that you use the `Default::default()` implementation of [`http::Response`](https://docs.rs/http/0.2.4/http/response/struct.Response.html) that by default returns something like HTTP 200 I believe. Just create the response with the appropriate HTTP error code and you are good to go :)
