### ISSUE TITLE
Receiving seems to be paused after `poll_next` of a wrapped stream returns `Poll::Pending` after updated v0.16.x

### ISSUE THREAD

**Issue by stackinspector** [snapview/tokio-tungstenite#206]
I wrapped `WebSocketStream` as another Stream (`futures::Stream`) to encapsulate some business logic in it, including filtering some messages (by returning `Poll::Pending` rather than `Poll::Ready(Some(payload))`)  received by `WebSocketStream` and not spreading them downstream. However, I found that after upgraded this crate to v0.16.x, new messages could no longer been received by downstream after the wrapped Stream returned `Poll::Pending` once. I set the logging level to debug or trace and found that `WebSocketStream` on the bottom also stopped receiving new messages, as if it was suspended. I tried to downgrade the version to v0.15.x and the problem disappeared. I'm confused about this problem, and I don't know if I'm having problems implementing it this way originally, or if I've found some hidden bug in this crate, and would like to get an answer.
The following code is an minimal example of the wrapped Stream with all of the business logics removed.
```rust
use std::{pin::Pin, task::{Context, Poll}};
use futures::{Stream, StreamExt, SinkExt, ready};
use tokio_tungstenite::{connect_async, tungstenite::{protocol::Message, Error as WsError}};

type WsStreamReceiver = futures::stream::SplitStream<tokio_tungstenite::WebSocketStream<tokio_tungstenite::MaybeTlsStream<tokio::net::TcpStream>>>;

struct WrappedStream {
    rx: WsStreamReceiver,
}

impl WrappedStream {
    async fn connect(url: String) -> Result<Self, WsError> {
        let (stream, _) = connect_async(url).await?;
        let (_tx, rx) = stream.split();
        Ok(Self { rx })
    }
}

impl Stream for WrappedStream {
    type Item = Vec<u8>;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        match ready!(Pin::new(&mut self.rx).poll_next(cx)) {
            Some(Ok(Message::Binary(payload))) => Poll::Ready(Some(payload)),
            Some(Ok(_)) => Poll::Pending,
            Some(Err(_)) | None => Poll::Ready(None),
        }
    }
}

#[tokio::main]
async fn main() {
    let mut stream = WrappedStream::connect("wss://example.com/example").await.unwrap();
    while let Some(payload) = stream.next().await {
        // do something with payload
    }
}
```

**Comment by sdroege** [comment]
> ```rust
>             Some(Ok(_)) => Poll::Pending,
> ```

You need to make sure that the underlying stream is storing a waker (or your wrapper streams needs to store that) whenever you return `Pending`. Otherwise there's no way the stream can be woken up again.

In your case the easiest would to to make `poll_next()` a loop and if a message is received that you want to throw away, you would simply iterate another time through the `poll_next()` of the underlying stream until it either returns `Pending` itself, returns a message you're interested in, ends up with an error or finishes.

**Comment by stackinspector** [comment]
I think that I got it. But what causes different versions of that crate have different behavior?

**Comment by sdroege** [comment]
I don't know, but your code could've only worked accidentally before :)

**Comment by application-developer-DA** [comment]
I don't even know what to add, @sdroege has already written a great explanation including the way to solve the problem :)
