### ISSUE TITLE
Question: is the closing handshake handled by tungstenite?

### ISSUE THREAD

**Issue by crowlKats** [snapview/tokio-tungstenite#207]
[RFC6455 states under section 1.4](https://datatracker.ietf.org/doc/html/rfc6455#section-1.4):
>    Either peer can send a control frame with data containing a specified
   control sequence to begin the closing handshake (detailed in
   Section 5.5.1).  Upon receiving such a frame, the other peer sends a
   Close frame in response, if it hasn't already sent one.  Upon
   receiving _that_ control frame, the first peer then closes the
   connection, safe in the knowledge that no further data is
   forthcoming.

Now, my question is, does tungstenite handle this (as in, if a close frame is received, it automatically sends a close frame, and if a close frame is sent, it waits for a closeframe to be received, and it makes this seamless) behind the scenes, or does the user of the crate need to manually handle the closing handshake? It does quite feel like tungstenite should be handling this, given that its part of the RFC's section for closing.

I guess this issue would make more sense in the tungstenite-rs repository, apologies.

**Comment by application-developer-DA** [comment]
Hi, sure, we handle this section as described in RFC ;)
