### ISSUE TITLE
Got panic on async connect

### ISSUE THREAD

**Issue by jaudiger** [snapview/tokio-tungstenite#212]
Hi,

Since the last release of the crate, I'm beggining to have a strange panic after trying to do an async connect with the following code:

```rust
    let header = Request::builder()
        .uri("ws://localhost:5683")
        .header(http::header::SEC_WEBSOCKET_PROTOCOL, "test")
        .body(())
        .unwrap(); // Safe
    let (mut websocket_client, _) = tokio_tungstenite::connect_async(header).await.unwrap();
```

I got:

```log
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Protocol(InvalidHeader("sec-websocket-key"))'
```

**Comment by sdroege** [comment]
You need to provide the `sec-websocket-key` and other headers yourself now if you create the request yourself.

Something like
```rust
        let req = Request::builder()
            .method("GET")
            .header("Host", host)
            .header("Connection", "Upgrade")
            .header("Upgrade", "websocket")
            .header("Sec-WebSocket-Version", "13")
            .header("Sec-WebSocket-Key", tungstenite::generate_key())
            .uri(self)
            .body(())?;
```

Or you go via `your_uri.into_client_request()` to get a default `Request` that you can then modify.

**Comment by application-developer-DA** [comment]
Ok, the question seems to be answered :)

Note it's the same issue [as described here](https://github.com/snapview/tungstenite-rs/issues/264).

As for the rationale, you can read the reasoning behind the change here:
- https://github.com/snapview/tungstenite-rs/pull/259
- https://github.com/snapview/tungstenite-rs/pull/267#issuecomment-1046920524

**Comment by jaudiger** [comment]
Yep, thanks.
