### ISSUE TITLE
Make accept_hdr_async accept async callback

### ISSUE THREAD

**Issue by jsimonrichard** [snapview/tokio-tungstenite#222]
This is a feature request:

It should be possible to pass an async callback to the `accept_hdr_async` function. For example, in a header handling function that I'm writing, I need to check the contents of a cookie against a redis cache on my server, and I'm using an asynchronous library to talk to redis. Being able to pass and async function directly to `accept_hdr_async` would be really helpful.

Let me know what you think.

Right now I'm going to try to use tokio to circumvent this issue, but please let me know if you have any better ideas. Also, let me know if you need anything from me; if I have the time I might submit a PR.

**Comment by sdroege** [comment]
See also https://github.com/snapview/tokio-tungstenite/issues/159 and https://github.com/sdroege/async-tungstenite/issues/70.

It will require changing the handshake code inside tungstenite to allow running asynchronously.

**Comment by jsimonrichard** [comment]
Thanks for getting back to me; I looked through the source code for both [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite) and [tungstenite](https://github.com/snapview/tungstenite-rs), and I see what you mean.
