### ISSUE TITLE
Error in example: `Error` doesn't implement `Display` (required by {})

### ISSUE THREAD

**Issue by ipconfiger** [snapview/tokio-tungstenite#227]
Example code can build, run, but with some error in IDE
![1651407125522](https://user-images.githubusercontent.com/950968/166145363-8cca13c9-d4cc-44b4-944e-e80a40f2e02b.jpg)

**Comment by application-developer-DA** [comment]
> code can build, run, but with some error in IDE

If the code builds and runs, but triggers an error in the IDE, then there is something wrong with the IDE or its configuration. Such things are outside of the responsibilities of the library 😉
