### ISSUE TITLE
How to improve max connections

### ISSUE THREAD

**Issue by adminSxs** [snapview/tokio-tungstenite#235]
I use examples/servers demo and join  myself logic,by jemeter test, the max connection in between 30-40, morethan 40 will response error: 
`WebSocket I/O error: No buffer space avaliable (maximum connections reached?): connect`

**Comment by application-developer-DA** [comment]
It seems like it's some problem with your operating system. The following `io::Error` is not generated by `tungstenite`.

A quick googling for the problem reveals that it might be related to something in Windows. Maybe a limit on sockets or something like this. Unfortunately, we can't help here as we don't know anything about the system, or environment and it lies outside the WebSocket logic. In other words: the same issue would occur if you start a regular non-WebSocket server by just using `TcpListener` from the Rust standard library.
