### ISSUE TITLE
Is there an example for tls server?

### ISSUE THREAD

**Issue by madmaxio** [snapview/tokio-tungstenite#24]
Can you add an example for tls server pls?

**Comment by agalakhov** [comment]
What's wrong with https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs ?

**Comment by application-developer-DA** [comment]
Yes, we can add it, but just to notice: the tls server example has nothing to do with tokio-tungstenite itself, as most of the code is just copy-pasting from https://github.com/tokio-rs/tokio-tls examples. Basically you just to configure TLS certificates properly (it's does not depend from tungstenite / tokio-tungstenite), and then pass it to tokio-tungstenite.

However we may add the example soon just to demonstrate that it works fine together with tokio-tls.

**Comment by madmaxio** [comment]
Ah I see, but if you add it would be still very helpfull, thx in advance
