### ISSUE TITLE
No Http Response when WebSocket protocol error: No "Connection: upgrade" header 

### ISSUE THREAD

**Issue by leptonyu** [snapview/tokio-tungstenite#243]
Is there any way to get the stream back from tungstenite?

**Comment by application-developer-DA** [comment]
Do I get it right, the issue that you're describing is that you're trying to establish a WebSocket connection, it fails and returns the error, but you would like to get the stream back from it? - If so, we currently don't really support this explicitly unfortunately, i.e. if you use `connect()`, then it all happens internally from `tungstenite` and I doubt that the stream returned from the `connect()` failure would be particularly useful. What might be more useful is to get the stream back in case you're using `client()` or some other function and want to access the internal stream after the failure. While we don't return such a stream back, you can easily workaround it by providing your own stream that can be clonable, i.e. pass one part to the `tungstenite`, `tungstenite` will consume the stream and then in case of failure you can still use the other counterpart that you had saved.

The tracking issue to return the stream back on failure is: https://github.com/snapview/tungstenite-rs/issues/51 (you've already found it though 😉)

**Comment by leptonyu** [comment]
Thanks for your reply.
I created a http buffer stream to preload the request from stream.
