### ISSUE TITLE
Unable to catch abnormal close connection behavior

### ISSUE THREAD

**Issue by CarbonPool** [snapview/tokio-tungstenite#248]
The windows client suddenly encounters a network disconnection, and the linux server cannot detect that the connection has been disconnected. I use "examples/server.rs" as an example. I am a novice in rust programming. Is there any related solution example, thank you very much help.

**Comment by daniel-abramov** [comment]
Yep, that's a typical question that we oftentimes get and it's not something that we can (or should) "solve" on the library level as it's just the TCP behavior.

I may suggest checking our explanation of how to handle this situation here:

- https://github.com/snapview/tokio-tungstenite/issues/234
- https://github.com/snapview/tokio-tungstenite/issues/241
- https://github.com/snapview/tungstenite-rs/issues/233

We enumerated several ways to handle this in the client code.

Hope this helps 🙂
