### ISSUE TITLE
How get the current state of the WebSocket connection?

### ISSUE THREAD

**Issue by A-kirami** [snapview/tokio-tungstenite#258]
Hi, I need to confirm the current state of the WebSocket connection.

What should I do? Thanks!

**Comment by daniel-abramov** [comment]
Sorry, I did not get the question. What do you mean by the state of the peer connection?

**Comment by A-kirami** [comment]
Like `WebSocket.readyState` in JavaScript.

https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState
