### ISSUE TITLE
IO error: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

### ISSUE THREAD

**Issue by rosejober** [snapview/tokio-tungstenite#265]
When I use tokio-tungstenite for websocket connection, features specify rustls-tls-webpki-roots. On some computers, there is an error in the title. This error seems to be due to the fact that set_certificate_verifier is not set in tls. Can it be fixed?

**Comment by daniel-abramov** [comment]
You have full control over which TLS connections are accepted and which are not. We're very flexible in that regard, i.e. check the  TLS` functions of `tokio-tungstenite`. Many of them do allow specifying a custom `Connector` if that's what you want, e.g. [`connect_async_tls_with_config`](https://docs.rs/tokio-tungstenite/latest/tokio_tungstenite/fn.connect_async_tls_with_config.html).

**Comment by rosejober** [comment]
It is recommended to add a parameter in WebSocketConfig to control whether to accept invalid certificates, just like the reqwest library.

**Comment by rosejober** [comment]
> You have full control over which TLS connections are accepted and which are not. We're very flexible in that regard, i.e. check the TLS functions of `tokio-tungstenite`. Many of them do allow specifying a custom `Connector` if that's what you want, e.g. [`connect_async_tls_with_config`](https://docs.rs/tokio-tungstenite/latest/tokio_tungstenite/fn.connect_async_tls_with_config.html).

It is recommended to add a parameter in WebSocketConfig to control whether to accept invalid certificates, just like the reqwest library.
