### ISSUE TITLE
Extracting web-socket headers after handshake

### ISSUE THREAD

**Issue by Relrin** [snapview/tokio-tungstenite#27]
Hello!

I'm looking a way to extract headers after handshake, between client and server. I'd like to make so because going check for a token in request, and if it doesn't exist, then return an error and shutdown the connection until token will be specified.

Does it possible to do something like this (part of this was taken from an [example](https://github.com/snapview/tungstenite-rs/blob/master/examples/server.rs#L13)):
```rust
accept_async(stream)
    .and_then(move |ws_stream| {
        let req = Request::try_parse(ws_stream).unwrap();
        println!("Received a new ws handshake");
        println!("The request's path is: {}", req.path);
        println!("The request's headers are:");
        for &(ref header, _ /* value */) in req.headers.iter() {
            println!("* {}", header);
        }
        Ok(ws_stream)
    })
    .and_then(move |ws_stream| {
        ...
    })
});
```
instead of implementing a special callback structure with [Callback trait](https://github.com/snapview/tungstenite-rs/blob/master/src/handshake/server.rs#L73) and using it with [accept_hdr_async](https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L90)? 
Because if I'm trying to do this via `accept_hdr_async` and send the message with code like this:
```rust
let auth_middleware_callback = |request: &Request| {
    let auth_middleware_inner = self.auth_middleware.clone();
    let processing_result = auth_middleware_inner.borrow().process_request(request);

    match processing_result {
        Ok(_) => Ok(None),
        Err(err) => {
            let formatted_error = format!("{}", err);
            let message = formatted_error.into_bytes();

            let (_, out) = stream.split();
            use futures::Stream;
            out.write_all(message).unwrap();
            out.flush();
            Err(TungsteniteError::Http(401))
        }
    }
};
```
Leads to the following error:
```
error[E0599]: no method named `split` found for type `tokio_core::net::TcpStream` in the current scope
  --> src/proxy.rs:65:50
   |
65 |                         let (_, out) = stream.split();
   |                                               ^^^^^
   |
   = note: the method `split` exists but the following trait bounds were not satisfied:
           `tokio_core::net::TcpStream : futures::Stream`
   = help: items from traits can only be used if the trait is in scope
   = note: the following traits are implemented but not in scope, perhaps add a `use` for one of them:
           candidate #1: `use std::io::BufRead;`
           candidate #2: `use futures::Stream;`
           candidate #3: `use tokio_core::io::Io;`
           candidate #4: `use tokio_io::AsyncRead;`

error: aborting due to previous error
```

An another reason why I want to do this, it is provide an access to customize the behavior for reverse proxy. Like if was specified `-v`/`--validate` option, then necessary to check and validate passed token after establishing a connection. Otherwise don't do an additional work.

**Comment by application-developer-DA** [comment]
The correct way to do it is indeed to use the `accept_hdr_async`, you can implement the behavior you want. But in your question you stated 2 contradicting requirements: first you told that you want to make a decision on whether to accept the websocket connection based on some headers specified in request, but then you tried to send a message **from this callback**. Apparently you cannot send a websocket message before awebsocket connection is fully established (i.e. the websocket handshake is completed). The callback is called when the request is received from the client, i.e. while the incoming handshake request is being processed, so it fits perfectly for the task you described.

If you want to reject the connection during the handshake, based on request value, just return an error from this callback and it will reject the incoming request with a given error. Notet: you cannot send a websocket message at this stage, because it **does not exist yet**.

**Comment by Relrin** [comment]
So, currently I will just close a connection if got an error during validation process (header is not specified or missed). It works good right now.
But... Do you have any plans to add a functionality, when I can get an access to headers after establishing the connection between server and client? (not with `accept_hdr_async` way, when you can't send a message)

**Comment by agalakhov** [comment]
No. Allowing access to all headers after they're processed means making and storing a copy of them. In most applications this is just waste of memory. You always can copy headers (or any useful part of them) in `accept_hdr` and process it later after the connection is established. That's what we do too in our project. The idea is quite simple:
```
let info_from_headers: Option<Something> = None;
...
accept_hdr_async(stream, |headers| {
    info_from_headers = Some(parse_some_headers(headers));
    Ok(None)
}).and_then(|connection| {
    send_some_reply(connection, info_from_headers, ...)
})
```
