### ISSUE TITLE
implement tokio_stream::StreamExt

### ISSUE THREAD

**Issue by toxeus** [snapview/tokio-tungstenite#272]
I'm a bit surprised that `tokio-tungstenite` doesn't implement [`tokio_stream::StreamExt`](https://docs.rs/tokio-stream/latest/tokio_stream/trait.StreamExt.html) but `futures::stream::StreamExt`. I think it wouldn't hurt to also implement the former for greater developer convenience.

**Comment by agalakhov** [comment]
The `tokio_stream::StreamExt` trait does not need to be implemented explicitly, it is implied for anything that implements `Stream`:
```rust
impl<St> StreamExt for St
where
    St: Stream + ?Sized,
```
so `tokio-tungstenite` has nothing to do with its implementation. It's [implemented by `tokio_stream`](https://docs.rs/tokio-stream/latest/src/tokio_stream/stream_ext.rs.html#1071). I wonder why it doesn't work for you.
