### ISSUE TITLE
Specifying values in Sec-WebSocket-Protocol header

### ISSUE THREAD

**Issue by Relrin** [snapview/tokio-tungstenite#28]
Hello!

I'm trying to append headers for a client, which is working with WebSocket connection, but he's receiving the following error in console of my browser, when creating a new connection between the client and server: 
```
WebSocket connection to 'ws://127.0.0.1:8080/' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received
```

For the client side I'm using a simple embedded JavaScript code, which is the part of HTML, for testing a reverse proxy functionality that have written with tokio-tungstenite:
```js
var ws = null;
var isopen = false;

window.onload = function() {

   ws = new WebSocket("ws://127.0.0.1:8080", "token");

   ws.onopen = function() {
      console.log("Connected!");
      isopen = true;
   };

   ws.onmessage = function(e) {
       console.log(e.data);
   };

   ws.onclose = function(e) {
      console.log("Connection closed.");
      ws = null;
      isopen = false;
   }
};

function sendOnStaticURL() {
   if (isopen) {
      ws.send(JSON.stringify({
         'content': {'test': 'value'}
         'url': '/api/matchmaking/search'
      }));
      console.log("sendOnStaticURL() clicked.");
   } else {
      console.log("Connection not opened.")
   }
}
```
So, the question here is: Does the tokio-tungstenite library let me to add values in "Sec-WebSocket-Protocol" header? Or it doesn't supported yet and I should to find an another way to provide a token (like `var ws = new WebSocket("ws://example.com/?token=testtoken`)?

**Comment by application-developer-DA** [comment]
You can append barely any headers in server's handshake response. Just return the list of the corresponding headers from the callback which is called when the server receives a websocket request (you already used this callback and mentioned it in your previous question).

**Comment by Relrin** [comment]
Thank you so much for the answer!
