### ISSUE TITLE
Can't disable certificate validation

### ISSUE THREAD

**Issue by thegamerx1** [snapview/tokio-tungstenite#297]
[tokio_tungstenite::Connector](https://docs.rs/tokio-tungstenite/0.20.0/tokio_tungstenite/enum.Connector.html#) requires [rustls::client::ClientConfig](https://docs.rs/rustls/latest/rustls/client/struct.ClientConfig.html#) but touching danguerous stuff like certificate validation converts it to a [rustls::client::DangerousClientConfig](https://docs.rs/rustls/latest/rustls/client/struct.DangerousClientConfig.html#) which [tokio_tungstenite::Connector](https://docs.rs/tokio-tungstenite/0.20.0/tokio_tungstenite/enum.Connector.html#) does not allow.

**Comment by daniel-abramov** [comment]
`DangerousClientConfig` has a `pub` field with the `ClientConfig` that it mutates.
