### ISSUE TITLE
new rustls 0.23.x is incompatible with the 0.22.x used by tokio-tungstenite

### ISSUE THREAD

**Issue by dottgonzo** [snapview/tokio-tungstenite#326]
to be able to use custom certificates or invalid certificates we need to use external rustls that recently was updated to support wasm. this latest version 0.23.0 has incompatible types with the one used by tokio-tungstenite

**Comment by Tahinli** [comment]
> to be able to use custom certificates or invalid certificates we need to use external rustls that recently was updated to support wasm. this latest version 0.23.0 has incompatible types with the one used by tokio-tungstenite

is this why I can't connect to my server that has rustls ?
![image](https://github.com/snapview/tokio-tungstenite/assets/96421894/6f1b05df-e944-40f1-a0ac-50b57fb4106e)

**Comment by Tahinli** [comment]
This situation breaks a lot of situation. Please update it.

**Comment by dottgonzo** [comment]
Tanks, i hope to see a new release on crates.io soon...
