### ISSUE TITLE
tokio-tungstenite not using version 0.22 of tungstenite

### ISSUE THREAD

**Issue by Its-Just-Nans** [snapview/tokio-tungstenite#334]
Hi @daniel-abramov 

Looks like the tungstenite https://github.com/snapview/tokio-tungstenite/blob/c1025d59ff15eeefc2dc07495fd6a8365cc6e0af/Cargo.toml#L36 is not at 0.22

That leads to have two **differents** versions of tungstenite in the same project

Is that normal ?

Maybe a solution would be to bump the two crates to 0.23
- `tungstenite@0.22` **-> `tungstenite@0.23`**
- `tokio-tungstenite@0.22` using `tungstenite@0.21` **-> `tokio-tungstenite@0.23` using `tungstenite@0.23`**

(and it will fix  https://github.com/snapview/tungstenite-rs/pull/427#pullrequestreview-2092151225)

**Comment by daniel-abramov** [comment]
Thanks for reporting that. I'm going to address that in a minute!
