### ISSUE TITLE
No option to enable `url` flag on `tungstenite`

### ISSUE THREAD

**Issue by cernicc** [snapview/tokio-tungstenite#337]
Hey. Thanks for the great work.

url was hidden behind a flag In 0.22.0. Currently there is no way to enable that flag.

**Comment by discosultan** [comment]
When is a new release of `tokio-tungstenite` planned that includes https://github.com/snapview/tokio-tungstenite/commit/db9ae7eb715e2b4a89deed4bc25d83e1d513d01f?
