### ISSUE TITLE
Are examples not applicable to the latest version?

### ISSUE THREAD

**Issue by istomyang** [snapview/tokio-tungstenite#352]
<img width="1018" alt="截屏2024-10-02 20 48 11" src="https://github.com/user-attachments/assets/51842578-bb07-49b3-a9e8-15c8a09a6bbe">

**Comment by daniel-abramov** [comment]
Yes, the examples should be correct.

Make sure that you have the necessary things imported and that they are used properly.

**Comment by istomyang** [comment]
> Yes, the examples should be correct.
> 
> Make sure that you have the necessary things imported and that they are used properly.

Thanks for your reply.

I noticed that it's necessary to explicitly add the `futures-util' dependency to your Cargo.toml.

It's a good idea to include this detail in the readme. It will help more newbies.
