### ISSUE TITLE
Add or update the server example to demonstrate closing gracefully from server-side/ctrl-c?

### ISSUE THREAD

**Issue by qtfkwk** [snapview/tokio-tungstenite#355]
Client-side close is already handled well in the [server example](https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs) ([line 71](https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs#L71)) and works as expected in my experience.

I want to handle closing and performing clean up tasks on the server side... from an interrupt signal / Control+C for example.

I've seen prior issues recommending calling the close() method on either the WebSocketStream or Sink after split...

In the [server example](https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs), it seems further complicated by `rx.map(Ok).forward(outgoing)` moving the Sink, `future::select(broadcast_incoming, receive_from_others).await` blocking, and neither WebSocketStream nor outgoing being `clone`able.

Can you please create a new example (starting with the server example) or update the server example to demonstrate how to accomplish this?

Many thanks!

**Comment by qtfkwk** [comment]
Think I have a functional workaround in my environment, which is a customized version of the server example.

**Have not tested the following**, but it should be faithful *but sanitized*:

```diff
--- examples/server.rs
+++ examples/server-ctrlc.rs
@@ -72,6 +72,11 @@
     peer_map.lock().unwrap().remove(&addr);
 }
 
+fn clean_up_connection(addr: &SocketAddr) {
+    println!("{addr} clean up");
+    // Place connection-specific clean up tasks here
+}
+
 #[tokio::main]
 async fn main() -> Result<(), IoError> {
     let addr = env::args().nth(1).unwrap_or_else(|| "127.0.0.1:8080".to_string());
@@ -83,6 +88,18 @@
     let listener = try_socket.expect("Failed to bind");
     println!("Listening on: {}", addr);
 
+    // Set interrupt handler
+    let my_state = state.clone();
+    tokio::spawn(async move {
+        tokio::signal::ctrl_c().await.unwrap();
+
+        // Handle each connection
+        my_state.lock().expect("lock state").keys().for_each(clean_up_connection);
+
+        // Exit server
+        std::process::exit(130);
+    });
+
     // Let's spawn the handling of each connection in a separate task.
     while let Ok((stream, addr)) = listener.accept().await {
         tokio::spawn(handle_connection(state.clone(), stream, addr));
```

This requires tokio's signal feature, so something like this might work:

```diff
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -25,6 +25,7 @@ native-tls-vendored = ["native-tls", "native-tls-crate/vendored", "tungstenite/n
 rustls-tls-native-roots = ["__rustls-tls", "rustls-native-certs"]
 rustls-tls-webpki-roots = ["__rustls-tls", "webpki-roots"]
 __rustls-tls = ["rustls", "rustls-pki-types", "tokio-rustls", "stream", "tungstenite/__rustls-tls", "handshake"]
+signal = ["tokio/signal"]
 stream = []
 url = ["tungstenite/url"]
 
@@ -100,6 +101,10 @@ required-features = ["handshake"]
 name = "server"
 required-features = ["handshake"]
 
+[[example]]
+name = "server-ctrlc"
+required-features = ["handshake", "signal"]
+
 [[example]]
 name = "server-headers"
 required-features = ["handshake"]
```

---

Copy of my `server-ctrl.rs`:

```rs
//! A chat server that broadcasts a message to all connections.
//!
//! This is a simple line-based server which accepts WebSocket connections,
//! reads lines from those connections, and broadcasts the lines to all other
//! connected clients.
//!
//! You can test this out by running:
//!
//!     cargo run --example server 127.0.0.1:12345
//!
//! And then in another window run:
//!
//!     cargo run --example client ws://127.0.0.1:12345/
//!
//! You can run the second command in multiple windows and then chat between the
//! two, seeing the messages from the other client as they're received. For all
//! connected clients they'll all join the same room and see everyone else's
//! messages.

use std::{
    collections::HashMap,
    env,
    io::Error as IoError,
    net::SocketAddr,
    sync::{Arc, Mutex},
};

use futures_channel::mpsc::{unbounded, UnboundedSender};
use futures_util::{future, pin_mut, stream::TryStreamExt, StreamExt};

use tokio::net::{TcpListener, TcpStream};
use tokio_tungstenite::tungstenite::protocol::Message;

type Tx = UnboundedSender<Message>;
type PeerMap = Arc<Mutex<HashMap<SocketAddr, Tx>>>;

async fn handle_connection(peer_map: PeerMap, raw_stream: TcpStream, addr: SocketAddr) {
    println!("Incoming TCP connection from: {}", addr);

    let ws_stream = tokio_tungstenite::accept_async(raw_stream)
        .await
        .expect("Error during the websocket handshake occurred");
    println!("WebSocket connection established: {}", addr);

    // Insert the write part of this peer to the peer map.
    let (tx, rx) = unbounded();
    peer_map.lock().unwrap().insert(addr, tx);

    let (outgoing, incoming) = ws_stream.split();

    let broadcast_incoming = incoming.try_for_each(|msg| {
        println!("Received a message from {}: {}", addr, msg.to_text().unwrap());
        let peers = peer_map.lock().unwrap();

        // We want to broadcast the message to everyone except ourselves.
        let broadcast_recipients =
            peers.iter().filter(|(peer_addr, _)| peer_addr != &&addr).map(|(_, ws_sink)| ws_sink);

        for recp in broadcast_recipients {
            recp.unbounded_send(msg.clone()).unwrap();
        }

        future::ok(())
    });

    let receive_from_others = rx.map(Ok).forward(outgoing);

    pin_mut!(broadcast_incoming, receive_from_others);
    future::select(broadcast_incoming, receive_from_others).await;

    println!("{} disconnected", &addr);
    peer_map.lock().unwrap().remove(&addr);
}

fn clean_up_connection(addr: &SocketAddr) {
    println!("{addr} clean up");
    // Place connection-specific clean up tasks here
}

#[tokio::main]
async fn main() -> Result<(), IoError> {
    let addr = env::args().nth(1).unwrap_or_else(|| "127.0.0.1:8080".to_string());

    let state = PeerMap::new(Mutex::new(HashMap::new()));

    // Create the event loop and TCP listener we'll accept connections on.
    let try_socket = TcpListener::bind(&addr).await;
    let listener = try_socket.expect("Failed to bind");
    println!("Listening on: {}", addr);

    // Set interrupt handler
    let my_state = state.clone();
    tokio::spawn(async move {
        tokio::signal::ctrl_c().await.unwrap();

        // Handle each connection
        my_state.lock().expect("lock state").keys().for_each(clean_up_connection);

        // Exit server
        std::process::exit(130);
    });

    // Let's spawn the handling of each connection in a separate task.
    while let Ok((stream, addr)) = listener.accept().await {
        tokio::spawn(handle_connection(state.clone(), stream, addr));
    }

    Ok(())
}
```

**Comment by qtfkwk** [comment]
This approach seems to be working for me so far...

- Client(s) heartbeat and attempt reconnect, so they don't need any special handling or closing.
- Ctrl+c already naturally kills the server and all connections but I'm storing session information in a database indexed by the addr / SocketAddr to a UUID-based session ID.
- I wanted session data in the database cleaned up on exit / interrupt, ideally by the server rather than some hacky or manual thing.
- Some of my failed attempts using `tokio::signal::ctrl_c()` left zombie connection threads running which had to be `kill -9`'d manually, so that's why the `std::process::exit()`.

Please let me know if you have any additional insights. Thanks again!

**Comment by daniel-abramov** [comment]
The general approach (waiting for the signal) is correct, but the implementation has some issues and is a bit far from the idiomatic approach. We did not have an example for this specific case because it is a reasonably typical task for the backend services written with Tokio (and can be handled differently depending on the use case) and it's not directly related to `tungstenite` or WebSockets.

There is an excellent example of how this may be implemented on a Tokio website: https://tokio.rs/tokio/topics/shutdown
Another great example is the `axum`'s graceful shutdown demo: https://github.com/tokio-rs/axum/blob/main/examples/graceful-shutdown/src/main.rs

In short, the typical approach is slightly different from what you've implemented so far; the general idea is as follows:
1. Typically, you collect the **join handles** for the tasks that require a graceful shutdown (`handle_connection()` in your case).
2. Additionally, each spawned task receives a channel over which it would receive a notification to shut down gracefully. The task typically uses `select! { ... }`, so that it runs until it completes or receives a signal to close and cleanup.
3. Then you listen for the required signal (similarly to how you implemented it), and once it happens, you send a close signal to all tasks that require a graceful shutdown. Tasks receive a signal, do the clean-ups, and end.
4. Meanwhile, you're waiting for them to complete by `await`ing their `JoinHandle`s.

Another great set of examples

I hope this helps!

**Comment by qtfkwk** [comment]
Okay... think I have it now... was way more complicated than anticipated. Perhaps there are better/easier ways? (Not particularly a fan of the `my_` clones at each async block border, but no idea what else to do.)

Agree this is more in tokio's scope than (tokio-)tungstenite's, and that the approach depends on what the code does. The difficulty is inversely proportional to expertise with tokio and it's the users' (my) responsibility. Notwithstanding, the two examples shared above hint at rather than give any solution (first is entry-level basic and the second uses axum's `with_graceful_shutdown`). I hoped for more, but am willing to do the work and share it in the hope it helps somebody (probably myself in about 6 months). Obviously, don't include this as an official example since it's out of scope; at least it is here.

Summary of changes:

- Created a CancellationToken and cloned it for the "Set interrupt handler" async block so it can call .cancel() after the ctrl+c
- Created another unbounded channel (set_tx, set_rx) with the receive end (set_rx) in the "Set interrupt handler" async block in a loop that calls .try_next() and awaits the sent future for each connection
- Wrapped the handle_connection call in a tokio::select! block alongside token.cancelled() and the connection clean up code
- Wrapped the previous tokio::select! block in an async block that sends it as a future to the sender side of the new unbounded channel (set_tx)
- Wrapped the listener accept while loop in another tokio::select! block alongside token.cancelled() so the main thread stops listening, does any clean up, and exits on cancellation

```diff
--- examples/server.rs
+++ examples/server-ctrlc.rs
@@ -30,6 +30,7 @@
 
 use tokio::net::{TcpListener, TcpStream};
 use tokio_tungstenite::tungstenite::protocol::Message;
+use tokio_util::sync::CancellationToken;
 
 type Tx = UnboundedSender<Message>;
 type PeerMap = Arc<Mutex<HashMap<SocketAddr, Tx>>>;
@@ -72,21 +73,76 @@
     peer_map.lock().unwrap().remove(&addr);
 }
 
+fn clean_up_connection(addr: &SocketAddr) {
+    println!("{addr} clean up");
+    // Place connection-specific clean up tasks here
+}
+
 #[tokio::main]
 async fn main() -> Result<(), IoError> {
     let addr = env::args().nth(1).unwrap_or_else(|| "127.0.0.1:8080".to_string());
 
     let state = PeerMap::new(Mutex::new(HashMap::new()));
+    let token = CancellationToken::new();
+    let (set_tx, mut set_rx) = futures_channel::mpsc::unbounded();
 
     // Create the event loop and TCP listener we'll accept connections on.
     let try_socket = TcpListener::bind(&addr).await;
     let listener = try_socket.expect("Failed to bind");
     println!("Listening on: {}", addr);
 
+    // Set interrupt handler
+    let my_state = state.clone();
+    let my_token = token.clone();
+    tokio::spawn(async move {
+        tokio::signal::ctrl_c().await.unwrap();
+
+        // Send cancellation
+        my_token.cancel();
+
+        // Wait for open connections to clean up
+        loop {
+            match set_rx.try_next() {
+                Ok(Some(h)) => {
+                    h.await;
+                }
+                Ok(None) => {
+                    break;
+                }
+                Err(e) => {
+                    eprintln!("Error: {e:?}");
+                    break;
+                }
+            }
+        }
+    });
+
     // Let's spawn the handling of each connection in a separate task.
-    while let Ok((stream, addr)) = listener.accept().await {
-        tokio::spawn(handle_connection(state.clone(), stream, addr));
+    let my_token = token.clone();
+    tokio::select! {
+        _ = async move {
+            while let Ok((stream, addr)) = listener.accept().await {
+                let my_state = state.clone();
+                let token = my_token.clone();
+                set_tx.unbounded_send(async move {
+                    let state = my_state.clone();
+                    tokio::select! {
+                        _ = handle_connection(state, stream, addr) => {}
+                        _ = token.cancelled() => {
+                            clean_up_connection(&addr);
+                            my_state.lock().unwrap().remove(&addr);
+                        }
+                    }
+                })
+                .unwrap();
+            }
+        } => {}
+        _ = token.cancelled() => {
+            // Clean up code for server can go here
+        }
     }
 
+    // Clean up code for server can go here
+
     Ok(())
 }
```

**Comment by qtfkwk** [comment]
I finally rewrote my code using your Axum example recommendation and it's working perfectly... thanks again!
