### ISSUE TITLE
Consider if Stream should turn Closed errors into just None

### ISSUE THREAD

**Issue by seanmonstar** [snapview/tokio-tungstenite#45]
It seems more common for `futures::Stream` to return `Ok(Async::Ready(None))` instead of an `Err` when the stream is closed. Perhaps the `impl Stream` in this crate should map `Error::ConnectionClosed` to just `None`?

**Comment by application-developer-DA** [comment]
Hm, that's an interesting point, I've also thought about that, but if we do so, then we cannot investigate the websocket close code, probably we should make the `Message` an enum, which contains not only user messages, pings and pongs, but also the closing message. In this case, it would be possible to do the thing.

**Comment by seanmonstar** [comment]
Yea, I think that makes a lot of sense. It seems that closing the socket is normal, not an error. In other networking concepts in Rust, closing of a socket cleanly is not an error either. For example, `Read::read()` returns `Ok(0)` on a clean close.
