### ISSUE TITLE
client: ping support

### ISSUE THREAD

**Issue by bbigras** [snapview/tokio-tungstenite#6]
If I use tokio-tungstenite as a client, my application seems to reply to pings from the server but I was wondering if tokio-tungstenite (as a client) supported sending pings and dropping the connection on ping timeouts.

I'm not sure if you want this to be tokio-tungstenite's job or the job of the users but I think the users' code would be a lot simpler if there was pings support in tokio-tungstenite.

**Comment by agalakhov** [comment]
There is support for user pings in core Tungstenite, it is just not wrapped for Tokio. To be done.

**Comment by application-developer-DA** [comment]
Yeah, it's a good question how to make this implementation and stay compatible with the `Stream` requirements. When you split the `WebSocketStream` into 2 halves: `Stream` (incoming messages) and `Sink` (outcoming messages), each of them is a stream of `Message`s. Thus we can push messages to the sink and retrieve messages from the sink.

One of the simpliest solutions which comes to my mind is to add an additional function to the `Message`, something like `Message::control(...)` or `Message::ping(...)`, in this case you can send it to the sink like any other message, so it's very simple and does not even require changes in the user's code. By the way, this would also solve #4.

**Comment by bbigras** [comment]
Any plans to implement this soon? I think it's an important feature to have reliable web sockets.

**Comment by application-developer-DA** [comment]
We will definitely implement this eventually, we require these things for our product, but at the moment they are not in a priority as we have many other tasks to do, unfortunately neither I nor Alexey had time to add this support, but it should not be a complex thing, we just have to find some time to add this and fix several relevant issues (you might have noticed that all these things are already implemented internally in `tungstenite-rs`, we just to update and extend the public interfaces of some modules).
