### ISSUE TITLE
Update tungstenite version dependency to 0.9

### ISSUE THREAD

**Issue by serzhiio** [snapview/tokio-tungstenite#60]
subj

**Comment by application-developer-DA** [comment]
Will be done soon, waiting for new 0.9.1 version to be published.

**Comment by application-developer-DA** [comment]
ping @agalakhov : I updated the crate to use the newest version of `tungstenite-rs`, please publish the new crate to crates.io

**Comment by application-developer-DA** [comment]
Done.
