### ISSUE TITLE
Example for handling connections

### ISSUE THREAD

**Issue by scraggelz** [snapview/tokio-tungstenite#66]
I'm having a hard time handling new connections. When a new stream connects I want to send messages directly back and forth between that client to establish username/etc. However, the examples aren't very clear to me on how to create a handle_connection function. 

I noticed in tungstenite-rs the autobahn server example does though. Is it similar to that? I've tried sending using the sink but I can't because ws_writer uses it.

Any advice would be great.

**Comment by application-developer-DA** [comment]
> When a new stream connects I want to send messages directly back and forth between that client

Do you want to write an echo-server?

> I noticed in tungstenite-rs the autobahn server example does though. Is it similar to that? 

We do have the same autobahn server example for `tokio-tungstenite`.

> I've tried sending using the sink but I can't because ws_writer uses it.

If you're talking about the chat server example that we have in our "examples" directory, then of course you can't use `sink` directly as it's consumed (folded). You might have noticed that there is an async MPSC channel created right before splitting the `ws_stream`. The receiving part of that MPSC channel is attached to sink, so you can use the sender part to send messages. There is a map of all connections which holds all users and their corresponding `tx` parts. The only reason the message is not echoed to the recipient back [is this line](https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs#L82). If you want, you can simply move your `tx` handle which corresponds to the client into your `for_each` future and just send replies to this `tx` whenever you receive a new message

P.S.: I think that a misunderstanding comes from the fact that the usage of the library implies a certain understanding of tokio framework basics. It might be helpful to take a look at [tokio docs](https://tokio.rs/docs/getting-started/echo/).
