### ISSUE TITLE
Cancelation clarification

### ISSUE THREAD

**Issue by SOF3** [snapview/tokio-tungstenite#81]
If I await `tokio::time::timeout(web_socket_stream.next())`, and the timeout happens before the socket receives a message (and so the `web_socket_stream.next()` future gets dropped), would this lead to skipping a message? Or is it OK to keep polling `web_socket_stream.next()` and ignore the result as long as it does not return `Poll::Ready`?

**Comment by agalakhov** [comment]
No, the message won't be skipped. Just make sure you don't drop the entire websocket.

**Comment by application-developer-DA** [comment]
This seems to have been clarified, hence closing.
