### ISSUE TITLE
New `tokio-runtime-worker` spawn each time `async_connect` is called

### ISSUE THREAD

**Issue by rtxm** [snapview/tokio-tungstenite#91]
I was surprised to see a new native thread being spawn for each new connection established by `async_connect`. What's the purpose?

**Comment by application-developer-DA** [comment]
`connect_async` does not spawn any threads on its own, but this crate relies on usage of Tokio as runtime "framework". The behavior depends on the way you configure the executor for Tokio. If I'm not mistaken, the default executor uses a work-stealing thread pool. In other words: you should probably check Tokio documentation and select the executor (or write your own) which suits your needs.

Hope this helps.

**Comment by rtxm** [comment]
I forgot to tell I'm using the basic scheduler.
