### ISSUE TITLE
send headers along with `connect_async`

### ISSUE THREAD

**Issue by EverlastingBugstopper** [snapview/tokio-tungstenite#92]
I need to send along some authentication headers along with a request to instantiate a websocket connection, is there a way I can do this?

**Comment by application-developer-DA** [comment]
Sure, as you can [see in the docs](https://docs.rs/tokio-tungstenite/0.10.1/tokio_tungstenite/fn.connect_async.html), the `connect_async` function takes a generic request (any type which implements a trait`. This trait is implemented for `httparse::Request`, which [allows you](https://docs.rs/httparse/1.3.4/httparse/struct.Request.html) to construct request, containing the required headers.

**Comment by EverlastingBugstopper** [comment]
oh, nice! thanks :)

**Comment by elderhammer** [comment]
My solution is to use [http::Request](https://docs.rs/http/0.2.9/http/request/struct.Request.html).
```Rust
let request = Request::builder()
    .uri(address)
    .header(auth_key, auth_value)
    .header("sec-websocket-key", "foo")
    .header("host", "server.example.com")
    .header("upgrade", "websocket")
    .header("connection", "upgrade")
    .header("sec-websocket-version", 13)
    .body(())
    .unwrap();
```
